cursor            #ffffff
cursor_text_color #32311f

foreground            #e6e2de
background            #0f0e0c
selection_foreground  #313128
selection_background  #c9c7ba
url_color             #c9c7ba

#: black 000000 767676
color0  #141312
color8  #363532
#: red cc0403 f2201f
color1  #2e2729
color9  #816d73
#: green 19cb00 23fd00
color2  #c9c7ba
color10 #e6e3d5
#: yellow cecb00 fffd00
color3  #c1cab5
color11 #dde6d0
#: blue 0d73cc 1a8fff
color4  #484834
color12 #ffffff
#: magenta cb1ed1 fd28ff
color5  #48473e
color13 #c9c7ba
#: cyan 0dcdcd 14ffff
color6  #41493a
color14 #ffffff
#: white dddddd ffffff
color7  #c9c7bb
color15 #e6e2de

mark1_foreground #1c1c0c
mark1_background #e6e4c8
mark2_foreground #1c1c14
mark2_background #e6e3d5
mark3_foreground #161e11
mark3_background #dde6d0

active_tab_foreground #32311f
active_tab_background #ffffff
inactive_tab_foreground #4a4935
inactive_tab_background #e6e4c8

active_border_color #ffffff
inactive_border_color #32311f
# bell_border_color #ff5a00