cursor            #c4c6d2
cursor_text_color #2d303a

foreground            #e5e2e2
background            #0e0e0f
selection_foreground  #2f3034
selection_background  #c7c6cb
url_color             #c7c6cb

#: black 000000 767676
color0  #131314
color8  #353435
#: red cc0403 f2201f
color1  #ffb4ab
color9  #93000a
#: green 19cb00 23fd00
color2  #c7c6cb
color10 #e3e2e7
#: yellow cecb00 fffd00
color3  #d4c2cb
color11 #f1dde7
#: blue 0d73cc 1a8fff
color4  #c4c6d2
color12 #e0e2ee
#: magenta cb1ed1 fd28ff
color5  #c7c6cb
color13 #e3e2e7
#: cyan 0dcdcd 14ffff
color6  #d4c2cb
color14 #f1dde7
#: white dddddd ffffff
color7  #c7c6cc
color15 #e5e2e2

mark1_foreground #181b24
mark1_background #e0e2ee
mark2_foreground #1a1b1f
mark2_background #e3e2e7
mark3_foreground #23181f
mark3_background #f1dde7

active_tab_foreground #2d303a
active_tab_background #c4c6d2
inactive_tab_foreground #adafbb
inactive_tab_background #21242d

active_border_color #c4c6d2
inactive_border_color #2d303a
# bell_border_color #ff5a00