require("hyprland.binds")
require("hyprland.colors")
require("hyprland.env")
require("hyprland.execs")
require("hyprland.general")
require("hyprland.input")
require("hyprland.monitors")
require("hyprland.rules")
