$terminal = kitty
$fileManager = dolphin
$menu = vicinae toggle
$qsConfig = ~/.config/quickshell

source = hyprland/general.conf
source = hyprland/binds.conf
source = hyprland/rules.conf
source = hyprland/execs.conf
source = hyprland/env.conf
