# exec-once = $terminal
# exec-once = nm-applet &
exec-once = hyprpaper &
exec-once = qs -c $qsConfig &
exec-once = vicinae server
exec-once = hyprctl setcursor Bibata-Modern-Classic 22
exec-once = easyeffects --hide-window --service-mode
exec-once = wl-paste --type text --watch bash -c 'cliphist store'
exec-once = wl-paste --type image --watch bash -c 'cliphist store'
exec-once = mako