hl.on("hyprland.start", function () 
  hl.exec_cmd("hyprpaper &")
  hl.exec_cmd("qs &")
  hl.exec_cmd("vicinae server")
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 22")
  hl.exec_cmd("easyeffects --hide-window --service-mode")
  hl.exec_cmd("wl-paste --type text --watch bash -c 'cliphist store'")
  hl.exec_cmd("wl-paste --type image --watch bash -c 'cliphist store'")
  hl.exec_cmd("mako")
end)