layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

layerrule {
    name = quickshell-blur
    blur = on
    match:namespace = quickshell
}

windowrule {
    name = Steam friends list float
    match:initial_title = negative:Steam
    match:class = steam
    float = on
}

windowrule = match:title ^(Quickshell Settings)$, float on
windowrule = match:title ^(Quickshell Overlay Backdrop)$, float on
windowrule = match:title ^(Quickshell Overlay Backdrop)$, size 100% 100%
windowrule = match:title ^(Quickshell Overlay Backdrop)$, move 0 0
windowrule = match:title ^(Quickshell Overlay)$, float on