layerrule {
    name = vicinae-blur
    blur = on
    ignore_alpha = 0
    match:namespace = vicinae
}

windowrule {
    name = Steam friends list float
    match:initial_title = negative:Steam
    match:class = steam
    float = on
}

windowrule = match:title ^(Quickshell Settings)$, float on