[global_tags]
  user = "admin"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb3-core:8181"]
  token = "<influxdb_token>"
  organization = ""
  bucket = "telegraf"

[[inputs.openweathermap]]
  app_id = "<app_id>"
  city_id = ["<city_id>"]
  lang = "en"
  fetch = ["weather"]
  base_url = "https://api.openweathermap.org/"
  interval = "10m"
  query_style = "individual"

[[inputs.mem]]
